<a href="https://colab.research.google.com/github/nivin18/RealTimeMLProjects/blob/master/Customer_Churn_Prdiction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import numpy as np
import pandas as pd

In [97]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [98]:
dataset.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [99]:
X = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1].values

In [100]:
x.head(10)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
5,645,44,8,113755.78,2,1,0,149756.71,0,1,1
6,822,50,7,0.00,2,1,1,10062.80,0,0,1
7,376,29,4,115046.74,4,1,0,119346.88,1,0,0
8,501,44,4,142051.07,2,0,1,74940.50,0,0,1
9,684,27,2,134603.88,1,1,1,71725.73,0,0,1

In [101]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [102]:
print(X['Geography'].value_counts())
print(X['Gender'].value_counts())
print(X['NumOfProducts'].value_counts())
print(X['HasCrCard'].value_counts())
print(X['IsActiveMember'].value_counts())

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64
Male      5457
Female    4543
Name: Gender, dtype: int64
1    5084
2    4590
3     266
4      60
Name: NumOfProducts, dtype: int64
1    7055
0    2945
Name: HasCrCard, dtype: int64
1    5151
0    4849
Name: IsActiveMember, dtype: int64

In [103]:
unique, counts = np.unique(y, return_counts=True)
print(np.asarray((unique, counts)))

[[   0    1]
 [7963 2037]]

describe function only takes numerical values

In [104]:
x.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.250900,0.247700,0.545700
std,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.433553,0.431698,0.497932
min,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,0.000000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,0.000000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,0.000000,1.000000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,1.000000,0.000000,1.000000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,1.000000

In [105]:
x.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Geography_Germany',
       'Geography_Spain', 'Gender_Male'],
      dtype='object')

By doing this we can is if there are any null values present

In [106]:
x.isnull().sum()

CreditScore          0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Geography_Germany    0
Geography_Spain      0
Gender_Male          0
dtype: int64

Shows data type

In [107]:
x.dtypes

CreditScore            int64
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Geography_Germany      uint8
Geography_Spain        uint8
Gender_Male            uint8
dtype: object

This function will convery to onehot encoding and remove one coloum

In [108]:
x = pd.get_dummies(x, drop_first = True)

Here france and female are removed to reduce the complexity

In [109]:
x.head(10)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
5,645,44,8,113755.78,2,1,0,149756.71,0,1,1
6,822,50,7,0.00,2,1,1,10062.80,0,0,1
7,376,29,4,115046.74,4,1,0,119346.88,1,0,0
8,501,44,4,142051.07,2,0,1,74940.50,0,0,1
9,684,27,2,134603.88,1,1,1,71725.73,0,0,1

Strarify function will prevent the model from being bais

In [110]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.15, stratify=y, random_state = 0)

In [111]:
print(x_train)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
5823          751   51       7  148074.79              1          1
2217          666   35       2  104832.49              1          1
6423          652   41       8  115144.68              1          1
5783          624   71       7       0.00              2          1
937           850   44       5  128605.32              1          0
...           ...  ...     ...        ...            ...        ...
2795          515   25       7   79543.59              1          0
1733          614   32       7   99462.80              2          1
4674          850   41       1  176958.46              2          0
6633          729   42       7       0.00              2          1
8389          743   25       6       0.00              2          1

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
5823               0        146411.41                  1                0
2217               0        175015.12                  0                1
6423               0        188905.43                  0                1
5783               1        108841.83                  0                0
937                1        171096.20                  1                0
...              ...              ...                ...              ...
2795               1         38772.82                  0                0
1733               1         51117.06                  1                0
4674               1        125806.30                  1                0
6633               0         58268.20                  0                1
8389               0        129740.11                  0                1

      Gender_Male
5823            0
2217            1
6423            1
5783            1
937             0
...           ...
2795            0
1733            1
4674            1
6633            0
8389            1

[8500 rows x 11 columns]

In [112]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [113]:
print(x_train)

[[ 1.03682098  1.15867808  0.69679344 ...  1.72232466 -0.57191626
  -1.09379268]
 [ 0.15827867 -0.37159838 -1.0351044  ... -0.58061063  1.74850772
   0.91425004]
 [ 0.01357758  0.20225529  1.043173   ... -0.58061063  1.74850772
   0.91425004]
 ...
 [ 2.06006438  0.20225529 -1.38148396 ...  1.72232466 -0.57191626
   0.91425004]
 [ 0.80943356  0.29789757  0.69679344 ... -0.58061063  1.74850772
  -1.09379268]
 [ 0.95413465 -1.32802118  0.35041387 ... -0.58061063  1.74850772
   0.91425004]]

Creating the model

In [114]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [115]:
y_pred = rf.predict(x_test)

In [116]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[1156   38]
 [ 174  132]]
0.8586666666666667

In [119]:
import pickle
pickle.dump(rf, open('customer_Churn_Prediction.pk1', 'wb'))